services:

  apache:
    container_name: ${APACHE_NAME}
    build:
      context: .
      args:
        TAG: ${APACHE_TAG}
    restart: always
    networks:
      - default
    ports:
      - ${APACHE_HTTP_PORT}:8080
      - ${APACHE_HTTPS_PORT}:8443
    environment:
      APP_ENV: ${APP_ENV}
      USER_ID: ${USER_ID}
      GROUP_ID: ${GROUP_ID}
      APACHE_REWRITE_MODULE_ENABLED: ${APACHE_REWRITE_MODULE_ENABLED}
      APACHE_LDAP_MODULE_ENABLED: ${APACHE_LDAP_MODULE_ENABLED}
      APACHE_EVASIVE_MODULE_ENABLED: ${APACHE_EVASIVE_MODULE_ENABLED}
      APACHE_DEFLATE_MODULE_ENABLED: ${APACHE_DEFLATE_MODULE_ENABLED}
      APACHE_ENV_MODULE_ENABLED: ${APACHE_ENV_MODULE_ENABLED}
      APACHE_EXPIRES_MODULE_ENABLED: ${APACHE_EXPIRES_MODULE_ENABLED}
      APACHE_EXT_FILTER_MODULE_ENABLED: ${APACHE_EXT_FILTER_MODULE_ENABLED}
      APACHE_FILTER_MODULE_ENABLED: ${APACHE_FILTER_MODULE_ENABLED}
      APACHE_HEADERS_MODULE_ENABLED: ${APACHE_HEADERS_MODULE_ENABLED}
      APACHE_MIME_MODULE_ENABLED: ${APACHE_MIME_MODULE_ENABLED}
      APACHE_SETENVIF_MODULE_ENABLED: ${APACHE_SETENVIF_MODULE_ENABLED}
      APACHE_HTTP2_MODULE_ENABLED: ${APACHE_HTTP2_MODULE_ENABLED}
      APACHE_SUBSTITUTE_MODULE_ENABLED: ${APACHE_SUBSTITUTE_MODULE_ENABLED}
      APACHE_SECURITY3_MODULE_ENABLED: ${APACHE_SECURITY3_MODULE_ENABLED}
      APACHE_REMOTEIP_MODULE_ENABLED: ${APACHE_REMOTEIP_MODULE_ENABLED}
      APACHE_PAGESPEED_MODULE_ENABLED: ${APACHE_PAGESPEED_MODULE_ENABLED}
      APACHE_AUTOINDEX_MODULE_ENABLED: ${APACHE_AUTOINDEX_MODULE_ENABLED}
      APACHE_DAV_MODULE_ENABLED: ${APACHE_DAV_MODULE_ENABLED}
